apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: argocd-cm 
data: 
  timeout.reconciliation: 60s
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login  - allows to login using UI
  accounts.ksmith: apiKey, login
  # disables user. User is enabled by default
  accounts.ksmith.enabled: "true"